# Schema for the configuration files of the Faros Login module.
faros_login.settings:
  type: config_object
  label: 'Faros Login settings'
  mapping:
    example:
      type: string
      label: 'Example'
