field.widget.settings.micon_menu:
  type: mapping
  label: 'Link with icon settings'
  mapping:
    placeholder_url:
      type: string
      label: 'Placeholder for URL'
    placeholder_title:
      type: label
      label: 'Placeholder for link text'
    packages:
      type: sequence
      label: 'Packages'
      sequence:
        type: string
        label: 'Package Id'
micon_menu.config:
  type: config_object
  label: 'Micon Menu settings'
  mapping:
    packages:
      type: sequence
      label: 'Packages'
      sequence:
        type: string
        label: 'Package Id'
