<?php

declare(strict_types=1);

/**
 * @file
 * Provides a company entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function faros_login_theme(): array {
  return [
    'faros_login_company' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for company templates.
 *
 * Default template: faros-login-company.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the company information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_faros_login_company(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
