field.formatter.settings.micon_link:
  type: mapping
  label: 'Link format settings'
  mapping:
    trim_length:
      type: integer
      label: 'Trim link text length'
    url_only:
      type: boolean
      label: 'URL only'
    url_plain:
      type: boolean
      label: 'Show URL as plain text'
    rel:
      type: string
      label: 'Add rel="nofollow" to links'
    target:
      type: string
      label: 'Open link in new window'
    title:
      type: string
      label: 'Link text'
    icon:
      type: string
      label: 'Link icon'
    position:
      type: string
      label: 'Icon position'
    text_only:
      type: boolean
      label: 'Text only'


field.widget.settings.micon_link:
  type: mapping
  label: 'Link with icon settings'
  mapping:
    placeholder_url:
      type: string
      label: 'Placeholder for URL'
    placeholder_title:
      type: label
      label: 'Placeholder for link text'
    packages:
      type: sequence
      label: 'Packages'
      sequence:
        type: string
        label: 'Micon ID'
    icon:
      type: string
      label: 'Link icon'
    position:
      type: boolean
      label: 'Allow icon position selection'
    target:
      type: boolean
      label: 'Allow target selection'
