<?php

/**
 * @file
 * Core event dispatcher submodule.
 */

use Drupal\core_event_dispatcher\Event\Theme\ThemeEvent;

// Core.
// @todo hook_mail()
//
// Entity.
// @todo hook_entity_view_mode_info_alter()
// @todo hook_entity_revision_create()
// @todo hook_entity_preload()
// @todo hook_entity_storage_load()
// @todo hook_entity_translation_create()
// @todo hook_entity_revision_delete()
// @todo hook_entity_prepare_view()
// @todo hook_entity_view_mode_alter()
// @todo hook_entity_view_display_alter()
// @todo hook_entity_display_build_alter()
// @todo hook_entity_prepare_form()
// @todo hook_entity_form_display_alter()
// @todo hook_entity_bundle_field_info()
// @todo hook_entity_field_storage_info()
// @todo hook_entity_field_storage_info_alter()
// @todo hook_entity_field_access_alter()
// @todo hook_entity_field_values_init()
//
// Form.
// @todo hook_ajax_render_alter()
// @todo hook_batch_alter()
//
// Language.
// @todo hook_transliteration_overrides_alter()
//
// Theme.
// @todo hook_form_system_theme_settings_alter()
// @todo hook_themes_uninstalled()
// @todo hook_extension()
// @todo hook_render_template()
// @todo hook_element_info_alter()
// @todo hook_library_info_build()
// @todo hook_js_settings_build()
// @todo hook_js_settings_alter()
// @todo hook_css_alter()
// @todo hook_page_attachments_alter()
//
// Token.
// @todo hook_token_info_alter()

/**
 * Implements hook_theme().
 *
 * {@inheritdoc}
 */
function core_event_dispatcher_theme(array $existing): array {
  /** @var \Drupal\hook_event_dispatcher\Manager\HookEventDispatcherManagerInterface $manager */
  $manager = Drupal::service('hook_event_dispatcher.manager');
  $event = new ThemeEvent($existing);
  $manager->register($event);
  return $event->getNewThemes();
}
