onlyone.settings:
  type: config_object
  label: 'Only One settings'
  mapping:
    onlyone_node_types:
      type: sequence
      label: 'Configured content types to have Only One node'
      sequence:
        type: string
        label: 'Content type machine name'
    onlyone_new_menu_entry:
      type: boolean
      label: 'Defines if a new menu entry will be created for the configured content types.'
    onlyone_redirect:
      type: boolean
      label: 'Defines where the user will be redirected if the content type is configured to have onlyone node.'
